const fs = require('fs');
const path = require('path');

const flagsDir = path.join(__dirname, '../flags');
const outputPath = path.join(__dirname, '../src/flagsData.ts');

function main() {
    if (!fs.existsSync(flagsDir)) {
        console.error('Flags directory does not exist. Please run download-flags.js first.');
        process.exit(1);
    }

    const files = fs.readdirSync(flagsDir);
    const flags = {};

    for (const file of files) {
        if (file.endsWith('.png')) {
            const code = path.basename(file, '.png').toUpperCase();
            // Read as base64
            const content = fs.readFileSync(path.join(flagsDir, file), 'base64');
            flags[code] = content;
        }
    }

    const fileContent = `// This file is auto-generated by compile-flags.js. Do not edit manually.
export const flagsData: Record<string, string> = ${JSON.stringify(flags, null, 2)};
`;

    fs.writeFileSync(outputPath, fileContent, 'utf8');
    console.log(`Successfully compiled ${Object.keys(flags).length} flags to ${outputPath}`);
}

main();
